apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: node-group
    instanceType: t4g.large
    minSize: 2
    maxSize: 4
    desiredCapacity: 2