name: Deploy OpenTelemetry Demo to EKS (Rollback Demo)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig using eksctl
        run: eksctl utils write-kubeconfig --cluster=${{ secrets.EKS_CLUSTER_NAME }} --region=${{ secrets.AWS_REGION }}

      - name: Install Good Version (Preparation)
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update
          helm upgrade --install otel-demo open-telemetry/opentelemetry-demo \
            --namespace otel-demo \
            --version 0.37.1 \
            --create-namespace

      - name: Attempt Bad Upgrade (simulate failure with invalid value)
        id: badupgrade
        continue-on-error: true
        run: |
          helm upgrade otel-demo open-telemetry/opentelemetry-demo \
            --namespace otel-demo \
            --set "image.repository=DOES_NOT_EXIST"

      - name: Rollback to previous revision if bad upgrade failed
        if: steps.badupgrade.outcome == 'failure'
        run: |
          echo "Upgrade failed. Rolling back to previous release..."
          helm rollback otel-demo 1 --namespace otel-demo

      - name: Show Helm History and Pod Status (after rollback)
        run: |
          echo "===== HELM HISTORY ====="
          helm history otel-demo -n otel-demo
          echo "===== POD STATUS ====="
          kubectl get pods -n otel-demo